name: scarf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py39h06a4308_0
  - python=3.9.15=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py39h06a4308_0
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - asttokens==2.2.1
    - backcall==0.2.0
    - charset-normalizer==2.1.1
    - chumpy==0.70
    - click==8.1.3
    - contourpy==1.0.6
    - cycler==0.11.0
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - executing==1.2.0
    - fonttools==4.38.0
    - fvcore==0.1.5.post20221122
    - gitdb==4.0.10
    - gitpython==3.1.29
    - idna==3.4
    - imageio==2.22.4
    - iopath==0.1.10
    - ipdb==0.13.9
    - ipython==8.7.0
    - jedi==0.18.2
    - kiwisolver==1.4.4
    - kornia==0.6.0
    - loguru==0.6.0
    - lpips==0.1.4
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - networkx==2.8.8
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - opencv-python==4.6.0.66
    - packaging==22.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - portalocker==2.6.0
    - promise==2.3
    - prompt-toolkit==3.0.36
    - protobuf==4.21.11
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.13.0
    - pymcubes==0.1.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pywavelets==1.4.1
    - pyyaml==5.1.1
    - requests==2.28.1
    - scikit-image==0.19.3
    - scipy==1.9.3
    - sentry-sdk==1.11.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - six==1.16.0
    - smmap==5.0.0
    - stack-data==0.6.2
    - tabulate==0.9.0
    - termcolor==2.1.1
    - tifffile==2022.10.10
    - toml==0.10.2
    - torch==1.13.0
    - torchmetrics==0.11.0
    - torchvision==0.14.0
    - tqdm==4.64.1
    - traitlets==5.7.0
    - trimesh==3.17.1
    - typing-extensions==4.4.0
    - urllib3==1.26.13
    - vulture==2.6
    - wandb==0.13.6
    - wcwidth==0.2.5
    - yacs==0.1.8